### ISSUE TITLE
Potential overflow/panic in 'sequence_number'

### ISSUE THREAD

**Issue by danieleades** [get-eventually/eventually-rs#187]
as pointed out in #186, the `sequence_number` in the event store and `Persisted` structs is a `u32` which could overflow/panic in implementations that require a *large* number of events. As in, truly massive.

I've stated a couple of concerns i have with the proposed solution in #186, but it's definitely a problem worth solving.

This actually ties in well with some ideas i'd had about using a timestamp as a sequence id.

One solution might be to make the event store generic over the sequence number type. Off the top of my head you'll probably need an `Ord` bound, but not much else. To make this backwards compatible (and reduce the total number of generics to grok) you could make `u32` the default.

```rust

pub struct Persisted<SourceId, T, Idx = u32>
   where Idx: Ord
{
    source_id: SourceId,
    version: u32,
    sequence_number: Idx,
    event: T,
}
```

**Comment by cortopy** [comment]
I actually had a go at this myself. See my branch [here](https://github.com/J3A/eventually-rs/tree/persisted-ord). I want to use timescaledb and I needed the sequence/version to hold a postgres type of `TIMESTAMPZ`. Chrono's `DateTime` is `Ord`, and so it also felt like the thing to do

I have to say that the change was very tricky. At the end of it, I felt like something wasn't right. The amount of generic declared types for the Traits was getting too verbose and complex

Then I realised that timescaledb doesn't need timestamps and can operate with BIGINT, so I created an alternative where I'm just changing the types from 32 to 64 bits (hence my PR). 

In fact, this turned out to be a much better solution. Rust's `chrono` timestamps have a subsecond precission of nanoseconds. However, postgres TIMESTAMP types can only store a precission of microseconds. By storing a BIGINT instead of TIMESTAMP, the precision of Rust's timestamps can be saved in the database too! 

I could submit a PR if you want as it's done already, but I thought this didn't fit with what you guys are currently doing with version 0.5 and trying to simplify things

**Comment by danieleades** [comment]
@cortopy thankyou for the explanation, that makes a lot of sense. I'll let @ar3s3ru weigh in here. The last thing this crate needs is *more* generics (that don't add value)! Using default types might take some of the sting out of it

**Comment by ar3s3ru** [comment]
Hey folks 👋🏻 

Thanks for creating and discussing the issue, and much apologies for jumping in so late 😞   
I have checked #186 but I will leave my answer here and link it to the PR, just so that the conversation is happening in one place 😄 

As @danieleades said, using signed integers for `sequence_number` and `version` doesn't make a lot of sense, as these _must_ be positive and monotonically increasing. In that regards, I think using `u64` instead should give enough breathing room (18446744073709551615 events).

To answer something in the PR:

>However, that may be confused with the first version of the event if a zero-index is used. If I ask myself: what is the version of an aggregate with no events? I may answer -1

Sequence numbers may be zero-based (as they're basically offsets) and depends on the underlying implementation, while I would enforce a bit more versions to be **one-based**. Version `0` doesn't make much sense to me, as versions are quite literally the length of a single Event Stream.

>All the database connectors I know cast database big integers to i64, as they can be indeed negative. I chose i64 to bring field types closer to what database clients will give

I don't think designing the library core types following common database drivers practices is a good way forward.

Let's focus on this use-case: we need to represent monotonically-increasing sequences, sometimes zero-based, sometimes one-based. The logical conclusion is to use unsigned integers. Now, I understand that overflow is an issue and we can address that: let's pick the highest precision number that is likely supported in a wide variety of situations. 64-bits does the trick just fine.

This way, we're well covered from the application perspective as to how many events we can publish.

However, now we have a different problem: some Event Store implementations might not support this kind of precision. In this case:
1. When streaming, we assume events have been successfully committed to the Store, so we can just type-cast from their type (e.g. `i64`) to `u64`.
2. When appending/inserting, we need to check the type casting (e.g. `u64` -> `i64`): does it overflow? Yes, then fail hard. No, then insert and keep going.

What do you think?

**Comment by danieleades** [comment]
i think `i64`s are very big for some applications, but perhaps make sense as a sensible *default*. I would still like to retain the ability to use `u32`, or even potentially use some kind of timestamp or namespaced value.
