### ISSUE TITLE
Simplify handle return type

### ISSUE THREAD

**Issue by sancho20021** [get-eventually/eventually-rs#246]
**Is your feature request related to a problem? Please describe.**
Complex return type `Result<Option<Vec<Self::Event>>, Self::Error>` in `aggregate::Aggregate::handle()`.
I'm not sure, but it seems that `Option` part is unnecessary, as empty vector has similar semantics to `Option::None`.

**Describe the solution you'd like**
`Result<Vec<Self::Event>, Self::Error>` instead of `Result<Option<Vec<Self::Event>>, Self::Error>`.

**Comment by ar3s3ru** [comment]
Hi @sancho20021, thank you for the reporting.

This issue seems to be connected to `v0.4.0`, right?
The API has changed in `v0.5.0`, but we haven't released that version yet.

This is how the API is supposed to work now for modelling a command on an Aggregate Root: https://github.com/get-eventually/eventually-rs/blob/b9f6e7cc5ed67e65bc850361a314e536af557c98/examples/bank-accounting/src/domain.rs#L160-L183

**Comment by sancho20021** [comment]
Yes, thank you. Sorry, I didn't notice that I was using an older version. Closing the issue.
